import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getCurrentUser } from '@/lib/auth-config';

// GET - Get topic coverage analysis
export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const subjectId = searchParams.get('subjectId');
    const classLevelId = searchParams.get('classLevelId');

    const userId = (user as any).id;

    // Build where clause
    const topicWhere: any = {};
    if (subjectId) topicWhere.subjectId = subjectId;
    if (classLevelId) topicWhere.classLevelId = classLevelId;

    // Get all topics
    const topics = await db.topic.findMany({
      where: topicWhere,
      include: {
        subject: true,
        classLevel: true,
        subtopics: true,
        _count: {
          select: { questions: true },
        },
      },
    });

    // Get user's question coverage per topic
    const coverageData = await Promise.all(
      topics.map(async (topic) => {
        // Questions generated by user for this topic
        const userQuestions = await db.question.count({
          where: {
            topicId: topic.id,
            sourceId: userId,
          },
        });

        // Total questions available for this topic
        const totalQuestions = topic._count.questions;

        // Get coverage record if exists
        const coverage = await db.topicCoverage.findUnique({
          where: {
            topicId_userId: {
              topicId: topic.id,
              userId,
            },
          },
        });

        // Calculate coverage percentage
        const coveragePercentage = totalQuestions > 0 
          ? Math.min(100, (userQuestions / 10) * 100) // Assume 10 questions = 100% coverage
          : 0;

        return {
          topic: {
            id: topic.id,
            name: topic.name,
            subject: topic.subject.name,
            classLevel: topic.classLevel.name,
            subtopicCount: topic.subtopics.length,
          },
          totalQuestions,
          userQuestions,
          coverage: coveragePercentage,
          lastGenerated: coverage?.lastGenerated,
        };
      })
    );

    // Group by subject
    const bySubject = coverageData.reduce((acc, item) => {
      const subject = item.topic.subject;
      if (!acc[subject]) {
        acc[subject] = {
          subject,
          topics: [],
          totalCoverage: 0,
          topicCount: 0,
        };
      }
      acc[subject].topics.push(item);
      acc[subject].totalCoverage += item.coverage;
      acc[subject].topicCount += 1;
      return acc;
    }, {} as Record<string, any>);

    // Calculate average coverage per subject
    Object.values(bySubject).forEach((s: any) => {
      s.averageCoverage = s.topicCount > 0 ? s.totalCoverage / s.topicCount : 0;
    });

    // Overall stats
    const overallCoverage = coverageData.length > 0
      ? coverageData.reduce((sum, t) => sum + t.coverage, 0) / coverageData.length
      : 0;

    // Topics needing attention (low coverage)
    const needsAttention = coverageData
      .filter(t => t.coverage < 30)
      .sort((a, b) => a.coverage - b.coverage)
      .slice(0, 10);

    return NextResponse.json({
      overallCoverage,
      bySubject: Object.values(bySubject),
      allTopics: coverageData,
      needsAttention,
      summary: {
        totalTopics: topics.length,
        covered: coverageData.filter(t => t.coverage >= 50).length,
        partial: coverageData.filter(t => t.coverage >= 20 && t.coverage < 50).length,
        uncovered: coverageData.filter(t => t.coverage < 20).length,
      },
    });
  } catch (error) {
    console.error('Topic coverage error:', error);
    return NextResponse.json({ error: 'Failed to fetch topic coverage' }, { status: 500 });
  }
}
